# Generated by Django 3.2.5 on 2021-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_loc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='station_name',
            field=models.CharField(max_length=150),
        ),
    ]
