# Generated by Django 3.2.5 on 2021-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_loc_app', '0002_alter_stationmodel_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_url', models.CharField(max_length=200)),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('grid_id', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
