# Generated by Django 3.2.5 on 2021-07-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_loc_app', '0003_spatialpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('temperature_unit', models.CharField(max_length=5)),
                ('min_wind_speed', models.FloatField()),
                ('max_wind_speed', models.FloatField()),
                ('wind_speed_unit', models.CharField(max_length=5)),
                ('icon_url', models.URLField()),
                ('short_description', models.CharField(blank=True, max_length=256, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('weather_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_loc_app.weatherforecast')),
            ],
        ),
    ]
