# Generated by Django 3.2.5 on 2021-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_loc_app', '0004_coordinates_weatherforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
    ]
